### ISSUE TITLE
Drobne propozycje

### ISSUE THREAD

**Issue by dembanakh** [tfkls/tempus#1]
To są tylko bardzo drobne (nie zbyt ważne) propozycje. Nie musicie je stosować jeśli macie dobry powód, albo nawet jeśli wam po prostu nie podoba się 😃 

---

https://github.com/TFKls/tempus/blob/34c2e00b8e59bca6d825664dd2ffd69b091d627a/src/main/java/dev/tfkls/tempus/command/NutritionCommand.java#L90
W takich przypadkach zazwyczaj używa się `players.iterator().next()`

---

https://github.com/TFKls/tempus/blob/34c2e00b8e59bca6d825664dd2ffd69b091d627a/src/main/java/dev/tfkls/tempus/command/NutritionCommand.java#L118
Po co tu Guava, czy po prostu `List.of` nie pasowałby?

---

https://github.com/TFKls/tempus/blob/34c2e00b8e59bca6d825664dd2ffd69b091d627a/src/main/java/dev/tfkls/tempus/core/Nutrition.java#L14-L52
```java
public enum Type {
  NONE(null, PlayerStatusEffector.NONE),
  CARBOHYDRATE(Tags.CARBOHYDRATE, Effects.CARBOHYDRATE),
  FAT(Tags.FAT, Effects.FAT),
  PROTEIN(Tags.PROTEIN, Effects.PROTEIN);

  TagKey<Item> tag;
  PlayerStatusEffector effector;

  Type(TagKey<Item> tag, PlayerStatusEffector effector) {
    this.tag = tag;
    this.effector = effector;
  }
}
```

---

https://github.com/TFKls/tempus/blob/34c2e00b8e59bca6d825664dd2ffd69b091d627a/src/main/java/dev/tfkls/tempus/mixin/PlayerEntityTemperatureMixin.java#L30-L46
https://docs.oracle.com/en/java/javase/17/language/switch-expressions.html
```java
switch (source.getType().msgId()) {
    case "inFire" -> temperatureManager.applySingular(20, 0.1f);
    case "onFire" -> temperatureManager.applySingular(20, 0.05f);
    case "lava" ->  temperatureManager.applySingular(30, 0.1f);
    case "hotFloor" -> temperatureManager.applySingular(15, 0.2f);
    case "lightningBolt" -> temperatureManager.applySingular(50, 0.3f);
    default -> {};
}
```

**Comment by tfkls** [comment]
Dziękujemy za uwagi – wszystkie zostały uwzględnione ponieważ również uznajemy takie rozwiązania za ładniejsze stylistycznie :)
